// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: commands.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *string                `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkRequest) Reset() {
	*x = WorkRequest{}
	mi := &file_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkRequest) ProtoMessage() {}

func (x *WorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkRequest.ProtoReflect.Descriptor instead.
func (*WorkRequest) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{0}
}

func (x *WorkRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type WorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        *int64                 `protobuf:"varint,1,opt,name=amount" json:"amount,omitempty"`
	NewBalance    *int64                 `protobuf:"varint,2,opt,name=new_balance,json=newBalance" json:"new_balance,omitempty"`
	Message       *string                `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkResponse) Reset() {
	*x = WorkResponse{}
	mi := &file_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkResponse) ProtoMessage() {}

func (x *WorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkResponse.ProtoReflect.Descriptor instead.
func (*WorkResponse) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{1}
}

func (x *WorkResponse) GetAmount() int64 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

func (x *WorkResponse) GetNewBalance() int64 {
	if x != nil && x.NewBalance != nil {
		return *x.NewBalance
	}
	return 0
}

func (x *WorkResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type PvpBattleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *string                `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	OpponentId    *string                `protobuf:"bytes,2,opt,name=opponent_id,json=opponentId" json:"opponent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PvpBattleRequest) Reset() {
	*x = PvpBattleRequest{}
	mi := &file_commands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PvpBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PvpBattleRequest) ProtoMessage() {}

func (x *PvpBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PvpBattleRequest.ProtoReflect.Descriptor instead.
func (*PvpBattleRequest) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{2}
}

func (x *PvpBattleRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *PvpBattleRequest) GetOpponentId() string {
	if x != nil && x.OpponentId != nil {
		return *x.OpponentId
	}
	return ""
}

type PvpBattleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      *string                `protobuf:"bytes,1,opt,name=battle_id,json=battleId" json:"battle_id,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PvpBattleResponse) Reset() {
	*x = PvpBattleResponse{}
	mi := &file_commands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PvpBattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PvpBattleResponse) ProtoMessage() {}

func (x *PvpBattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PvpBattleResponse.ProtoReflect.Descriptor instead.
func (*PvpBattleResponse) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{3}
}

func (x *PvpBattleResponse) GetBattleId() string {
	if x != nil && x.BattleId != nil {
		return *x.BattleId
	}
	return ""
}

func (x *PvpBattleResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type SelectSkillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      *string                `protobuf:"bytes,1,opt,name=battle_id,json=battleId" json:"battle_id,omitempty"`
	UserId        *string                `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Skills        []string               `protobuf:"bytes,3,rep,name=skills" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectSkillsRequest) Reset() {
	*x = SelectSkillsRequest{}
	mi := &file_commands_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectSkillsRequest) ProtoMessage() {}

func (x *SelectSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectSkillsRequest.ProtoReflect.Descriptor instead.
func (*SelectSkillsRequest) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{4}
}

func (x *SelectSkillsRequest) GetBattleId() string {
	if x != nil && x.BattleId != nil {
		return *x.BattleId
	}
	return ""
}

func (x *SelectSkillsRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *SelectSkillsRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

type SelectSkillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *string                `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectSkillsResponse) Reset() {
	*x = SelectSkillsResponse{}
	mi := &file_commands_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectSkillsResponse) ProtoMessage() {}

func (x *SelectSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectSkillsResponse.ProtoReflect.Descriptor instead.
func (*SelectSkillsResponse) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{5}
}

func (x *SelectSkillsResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       map[string]string      `protobuf:"bytes,1,rep,name=details" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_commands_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_commands_proto protoreflect.FileDescriptor

const file_commands_proto_rawDesc = "" +
	"\n" +
	"\x0ecommands.proto\x12\x11bestorpg.commands\"%\n" +
	"\vWorkRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"a\n" +
	"\fWorkResponse\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12\x1f\n" +
	"\vnew_balance\x18\x02 \x01(\x03R\n" +
	"newBalance\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"L\n" +
	"\x10PvpBattleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vopponent_id\x18\x02 \x01(\tR\n" +
	"opponentId\"J\n" +
	"\x11PvpBattleResponse\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"c\n" +
	"\x13SelectSkillsRequest\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06skills\x18\x03 \x03(\tR\x06skills\"0\n" +
	"\x14SelectSkillsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x84\x01\n" +
	"\x05Error\x12?\n" +
	"\adetails\x18\x01 \x03(\v2%.bestorpg.commands.Error.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x8c\x02\n" +
	"\bCommands\x12G\n" +
	"\x04Work\x12\x1e.bestorpg.commands.WorkRequest\x1a\x1f.bestorpg.commands.WorkResponse\x12V\n" +
	"\tPvpBattle\x12#.bestorpg.commands.PvpBattleRequest\x1a$.bestorpg.commands.PvpBattleResponse\x12_\n" +
	"\fSelectSkills\x12&.bestorpg.commands.SelectSkillsRequest\x1a'.bestorpg.commands.SelectSkillsResponseB(Z& pineappletooth/bestoRpg/pkg/api/protob\beditionsp\xe8\a"

var (
	file_commands_proto_rawDescOnce sync.Once
	file_commands_proto_rawDescData []byte
)

func file_commands_proto_rawDescGZIP() []byte {
	file_commands_proto_rawDescOnce.Do(func() {
		file_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commands_proto_rawDesc), len(file_commands_proto_rawDesc)))
	})
	return file_commands_proto_rawDescData
}

var file_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_commands_proto_goTypes = []any{
	(*WorkRequest)(nil),          // 0: bestorpg.commands.WorkRequest
	(*WorkResponse)(nil),         // 1: bestorpg.commands.WorkResponse
	(*PvpBattleRequest)(nil),     // 2: bestorpg.commands.PvpBattleRequest
	(*PvpBattleResponse)(nil),    // 3: bestorpg.commands.PvpBattleResponse
	(*SelectSkillsRequest)(nil),  // 4: bestorpg.commands.SelectSkillsRequest
	(*SelectSkillsResponse)(nil), // 5: bestorpg.commands.SelectSkillsResponse
	(*Error)(nil),                // 6: bestorpg.commands.Error
	nil,                          // 7: bestorpg.commands.Error.DetailsEntry
}
var file_commands_proto_depIdxs = []int32{
	7, // 0: bestorpg.commands.Error.details:type_name -> bestorpg.commands.Error.DetailsEntry
	0, // 1: bestorpg.commands.Commands.Work:input_type -> bestorpg.commands.WorkRequest
	2, // 2: bestorpg.commands.Commands.PvpBattle:input_type -> bestorpg.commands.PvpBattleRequest
	4, // 3: bestorpg.commands.Commands.SelectSkills:input_type -> bestorpg.commands.SelectSkillsRequest
	1, // 4: bestorpg.commands.Commands.Work:output_type -> bestorpg.commands.WorkResponse
	3, // 5: bestorpg.commands.Commands.PvpBattle:output_type -> bestorpg.commands.PvpBattleResponse
	5, // 6: bestorpg.commands.Commands.SelectSkills:output_type -> bestorpg.commands.SelectSkillsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_commands_proto_init() }
func file_commands_proto_init() {
	if File_commands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commands_proto_rawDesc), len(file_commands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_commands_proto_goTypes,
		DependencyIndexes: file_commands_proto_depIdxs,
		MessageInfos:      file_commands_proto_msgTypes,
	}.Build()
	File_commands_proto = out.File
	file_commands_proto_goTypes = nil
	file_commands_proto_depIdxs = nil
}
